// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.

class Solution {
public:
  char findTheDifference(string s, string t) {
    unordered_map<char, int> m;
    for (char c : s) m[c]++;
    for (char c : t) {
      if (m[c]-- < 0)
        return false;
    }
    return 0;
  }
}
